### ISSUE TITLE
Manglende dokumentation

### ISSUE THREAD

**Issue by andtra** [iobear/dashgoat#1]
I følge dokumentationen skulle dette være nok til at starte dashgoat

```
 ./dashgoat -updatekey test
```

Applikationen starter så ikke med fejlen
```
Cant read Config file dashgoat.yaml
```

Der er ingen dokumenation på hvad der skal stå i yaml filen.

**Comment by iobear** [comment]
Ahh yes, I forgot the dashgoat.yaml in the root dir. Please try again.

**Comment by iobear** [comment]
I have updated the Readme file and added a dashGoat.postman_collection.json file to test the API calls, via Postman / Insomnia.
